# Generated by Django 5.1.3 on 2025-01-09 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("device_id", models.IntegerField(unique=True)),
                (
                    "tile_label",
                    models.CharField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("A3", "A3"),
                            ("A4", "A4"),
                            ("A5", "A5"),
                            ("A6", "A6"),
                            ("A7", "A7"),
                            ("A8", "A8"),
                            ("A9", "A9"),
                            ("A10", "A10"),
                            ("A11", "A11"),
                            ("A12", "A12"),
                            ("A13", "A13"),
                            ("A14", "A14"),
                        ],
                        max_length=3,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "arena",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
