# Generated by Django 5.1.3 on 2025-01-09 01:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="device",
            unique_together={("arena", "tile_label")},
        ),
    ]
