# Generated by Django 5.1.3 on 2025-01-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_alter_device_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="tile_label",
            field=models.CharField(
                choices=[
                    ("A1", "A1"),
                    ("A2", "A2"),
                    ("A3", "A3"),
                    ("A4", "A4"),
                    ("A5", "A5"),
                    ("A6", "A6"),
                    ("A7", "A7"),
                    ("A8", "A8"),
                    ("A9", "A9"),
                    ("A10", "A10"),
                    ("A11", "A11"),
                    ("A12", "A12"),
                    ("A13", "A13"),
                    ("A14", "A14"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
