# Generated by Django 5.1.3 on 2025-01-09 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_device_tile_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="arena",
        ),
        migrations.DeleteModel(
            name="Arena",
        ),
        migrations.DeleteModel(
            name="Device",
        ),
    ]
