# Generated by Django 5.1.3 on 2025-01-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arena", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arena",
            name="password",
            field=models.CharField(default="defaultpassword", max_length=128),
        ),
    ]
