# Generated by Django 5.1.3 on 2025-01-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arena", "0002_alter_arena_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="arena",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="arena",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="arena",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="arena",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
