# Generated by Django 5.1.3 on 2025-01-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arena", "0003_arena_email_alter_arena_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arena",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
