# Generated by Django 5.1.3 on 2025-01-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arena_name", models.CharField(max_length=100, unique=True)),
                ("brightness", models.IntegerField(default=75)),
            ],
        ),
    ]
