# Generated by Django 5.1.3 on 2025-03-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_verified",
            field=models.BooleanField(default=False),
        ),
    ]
